version: '3'

services:
  web:
    image: python:3.8
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: mydatabase

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
